import PDFDocument from "pdfkit";
import type { GuideInput } from "./guide-prompt";

const NAVY = "#425C47";
const GOLD = "#C9A84C";
const TEXT_GRAY = "#4A4A6A";

function getGuideLanguage(input: GuideInput): "fr" | "en" {
  return input.language === "en" ? "en" : "fr";
}

function getOpeningHoursNotice(language: "fr" | "en"): string {
  return language === "en"
    ? "Opening hours shown are indicative and may vary. Always check before your visit."
    : "Les horaires indiqués sont donnés à titre indicatif et peuvent varier. Vérifiez toujours avant votre visite.";
}

function getDisclaimer(language: "fr" | "en"): string {
  return language === "en"
    ? "This guide was generated by artificial intelligence. The information provided is indicative and may not be exact or up to date. Opening hours, closing days and access conditions may change without notice. TravelGuide AI cannot be held responsible for errors, omissions, exceptional closures or unforeseen schedule changes. We recommend checking official sources before each visit."
    : "Ce guide a été généré par intelligence artificielle. Les informations fournies sont données à titre indicatif et peuvent ne pas être exactes ou à jour. Les horaires, jours de fermeture et conditions d'accès peuvent changer sans préavis. TravelGuide AI ne saurait être tenu responsable d'éventuelles erreurs, omissions, fermetures exceptionnelles ou modifications d'horaires imprévues. Nous vous recommandons de vérifier les sources officielles avant chaque visite.";
}

function stripEmojis(text: string): string {
  return text
    .replace(
      /[\u{1F300}-\u{1F9FF}]|[\u{2600}-\u{26FF}]|[\u{2700}-\u{27BF}]|[\u{1F000}-\u{1F02F}]|[\u{1F0A0}-\u{1F0FF}]|[\u{1F100}-\u{1F1FF}]|[\u{1F200}-\u{1F2FF}]|[\u{1F004}]|[\u{1F0CF}]|[\u{1F170}-\u{1F171}]|[\u{1F17E}-\u{1F17F}]|[\u{1F18E}]|[\u{3030}]|[\u{2B50}]|[\u{2B55}]|[\u{2934}-\u{2935}]|[\u{2B05}-\u{2B07}]|[\u{2B1B}-\u{2B1C}]|[\u{3297}]|[\u{3299}]|[\u{303D}]|[\u{00A9}]|[\u{00AE}]|[\u{2122}]|[\u{23F3}]|[\u{24C2}]|[\u{23E9}-\u{23F3}]|[\u{25AA}-\u{25AB}]|[\u{25B6}]|[\u{25C0}]|[\u{25FB}-\u{25FE}]|[\u{2614}-\u{2615}]|[\u{2648}-\u{2653}]|[\u{267F}]|[\u{2693}]|[\u{26A1}]|[\u{26AA}-\u{26AB}]|[\u{26BD}-\u{26BE}]|[\u{26C4}-\u{26C5}]|[\u{26CE}]|[\u{26D4}]|[\u{26EA}]|[\u{26F2}-\u{26F3}]|[\u{26F5}]|[\u{26FA}]|[\u{26FD}]|[\u{2702}]|[\u{2705}]|[\u{2708}-\u{270D}]|[\u{270F}]|[\u{2712}]|[\u{2714}]|[\u{2716}]|[\u{271D}]|[\u{2721}]|[\u{2728}]|[\u{2733}-\u{2734}]|[\u{2744}]|[\u{2747}]|[\u{274C}]|[\u{274E}]|[\u{2753}-\u{2755}]|[\u{2757}]|[\u{2763}-\u{2764}]|[\u{2795}-\u{2797}]|[\u{27A1}]|[\u{27B0}]|[\u{27BF}]|[\u{2934}-\u{2935}]|[\u{2B05}-\u{2B07}]/gu,
      ""
    )
    .replace(/[╔╗╚╝║╠═]/g, "")
    .replace(/[☐☑]/g, "-")
    .replace(/[━]/g, "-")
    .trim();
}

function parseSections(content: string): Array<{ title: string; body: string }> {
  const separatorRegex = /─{20,}/g;
  const parts = content.split(separatorRegex);
  const sections: Array<{ title: string; body: string }> = [];

  for (let i = 0; i < parts.length; i++) {
    const part = parts[i].trim();
    if (!part) continue;
    const lines = part.split("\n").filter((l) => l.trim());
    if (lines.length === 0) continue;
    const title = stripEmojis(lines[0]).trim();
    const body = lines
      .slice(1)
      .map((l) => stripEmojis(l))
      .join("\n");
    if (title || body) {
      sections.push({ title, body });
    }
  }
  return sections;
}

export async function generateGuidePDF(
  input: GuideInput,
  aiContent: string
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const language = getGuideLanguage(input);
    const isEnglish = language === "en";
    const disclaimer = getDisclaimer(language);
    const openingHoursNotice = getOpeningHoursNotice(language);

    const doc = new PDFDocument({
      margin: 55,
      size: "A4",
      info: {
        Title: `${isEnglish ? "Travel guide" : "Guide de voyage"} — ${input.destination}`,
        Author: "TravelGuide AI",
        Subject: `${isEnglish ? "Your personalized guide for" : "Votre guide personnalisé pour"} ${input.destination}`,
      },
    });

    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const W = doc.page.width;
    const H = doc.page.height;
    const MARGIN = 55;
    const CONTENT_W = W - MARGIN * 2;

    // ─── COVER PAGE ───────────────────────────────────────────────────────────
    doc.rect(0, 0, W, H).fill(NAVY);

    // Decorative gold bar
    doc.rect(MARGIN, 70, 60, 4).fill(GOLD);

    // Brand
    doc
      .fillColor("white")
      .fontSize(11)
      .font("Helvetica")
      .text("TravelGuide AI", MARGIN, 88, { characterSpacing: 2 });

    // Main title (destination)
    const destTitle = input.destination.toUpperCase();
    doc
      .fillColor("white")
      .fontSize(38)
      .font("Helvetica-Bold")
      .text(destTitle, MARGIN, 160, { width: CONTENT_W, lineGap: 4 });

    // Duration badge
    const titleHeight = doc.currentLineHeight(true);
    const titleY = 160 + titleHeight + 20;
    doc
      .fillColor(GOLD)
      .fontSize(14)
      .font("Helvetica-Bold")
      .text(input.duration.toUpperCase(), MARGIN, titleY + 10);

    // Subtitle details
    doc
      .fillColor("rgba(255,255,255,0.65)")
      .fontSize(10)
      .font("Helvetica")
      .text(
        `${input.compagnie}  •  ${input.budget}  •  ${input.hebergement}`,
        MARGIN,
        titleY + 38
      );

    // Cover decorative section list
    const sections = [
      isEnglish ? "Day-by-day itinerary" : "Itinéraire jour par jour",
      isEnglish ? "Restaurants & food" : "Restaurants & gastronomie",
      isEnglish ? "Activities & places to visit" : "Activités & lieux à visiter",
      isEnglish ? "Local practical tips" : "Conseils pratiques locaux",
      ...(isLongTrip(input.duration)
        ? [
            isEnglish ? "Recommended accommodation" : "Hébergements recommandés",
            isEnglish ? "Off-the-beaten-path excursions" : "Excursions hors sentiers battus",
          ]
        : []),
    ];
    const listY = H - 220;
    doc
      .fillColor("rgba(255,255,255,0.4)")
      .fontSize(8)
      .font("Helvetica")
      .text(isEnglish ? "GUIDE CONTENT" : "CONTENU DU GUIDE", MARGIN, listY, { characterSpacing: 1.5 });

    sections.forEach((s, i) => {
      doc
        .fillColor("rgba(255,255,255,0.7)")
        .fontSize(9)
        .text(`• ${s}`, MARGIN, listY + 16 + i * 14);
    });

    // Generated date
    doc
      .fillColor("rgba(255,255,255,0.35)")
      .fontSize(8)
      .text(
        `${isEnglish ? "Generated on" : "Généré le"} ${new Date().toLocaleDateString(isEnglish ? "en-US" : "fr-FR", {
          day: "numeric",
          month: "long",
          year: "numeric",
        })}`,
        MARGIN,
        H - 60
      );

    // ─── CONTENT PAGES ────────────────────────────────────────────────────────
    const parsedSections = parseSections(aiContent);

    for (const section of parsedSections) {
      doc.addPage();
      addPageHeader(doc, input.destination, W, MARGIN);

      // Section title
      if (section.title) {
        const isIntroSection = /INTRODUCTION/i.test(section.title);

        doc.rect(MARGIN, 80, CONTENT_W, 2).fill(GOLD);
        doc
          .fillColor(NAVY)
          .fontSize(16)
          .font("Helvetica-Bold")
          .text(section.title, MARGIN, 90, { width: CONTENT_W });
        doc.moveDown(0.8);

        if (isIntroSection) {
          const noticeY = doc.y;
          doc.roundedRect(MARGIN, noticeY, CONTENT_W, 46, 8).fill("#FFF8E8");
          doc
            .fillColor("#5A4A10")
            .fontSize(8.8)
            .font("Helvetica-Bold")
            .text(isEnglish ? "Important note" : "Note importante", MARGIN + 12, noticeY + 10, {
              width: CONTENT_W - 24,
            });
          doc
            .fillColor("#5A4A10")
            .fontSize(8.5)
            .font("Helvetica")
            .text(openingHoursNotice, MARGIN + 12, noticeY + 24, {
              width: CONTENT_W - 24,
              lineGap: 2,
            });
          doc.y = noticeY + 56;
        }
      }

      // Section body — render paragraph by paragraph
      const paragraphs = section.body.split("\n").filter((l) => l.trim());
      for (const para of paragraphs) {
        const line = para.trim();
        if (!line) continue;

        // Detect day headers like "JOUR 1", "DAY 1"
        const isDayHeader = /^(JOUR|DAY|JOURNÉE)\s+\d+/i.test(line);
        const isBullet = line.startsWith("•") || line.startsWith("-") || line.startsWith("*");
        const isNumbered = /^\d+\./.test(line);
        const isSub = line.startsWith("→") || line.startsWith(">");

        if (isDayHeader) {
          doc.moveDown(0.5);
          doc.rect(MARGIN, doc.y, CONTENT_W, 22).fill("#EEE9E0");
          doc
            .fillColor(NAVY)
            .fontSize(11)
            .font("Helvetica-Bold")
            .text(line, MARGIN + 8, doc.y + 5, { width: CONTENT_W - 16 });
          doc.moveDown(0.6);
        } else if (isBullet || isNumbered) {
          doc
            .fillColor(TEXT_GRAY)
            .fontSize(9.5)
            .font("Helvetica")
            .text(line, MARGIN + 8, doc.y, { width: CONTENT_W - 8, lineGap: 2 });
          doc.moveDown(0.25);
        } else if (isSub) {
          doc
            .fillColor(TEXT_GRAY)
            .fontSize(8.5)
            .font("Helvetica-Oblique")
            .text(line, MARGIN + 16, doc.y, { width: CONTENT_W - 16, lineGap: 2 });
          doc.moveDown(0.2);
        } else {
          doc
            .fillColor(NAVY)
            .fontSize(9.5)
            .font("Helvetica")
            .text(line, MARGIN, doc.y, { width: CONTENT_W, lineGap: 3 });
          doc.moveDown(0.35);
        }
      }
    }

    // ─── DISCLAIMER PAGE ──────────────────────────────────────────────────────
    doc.addPage();
    addPageHeader(doc, input.destination, W, MARGIN);

    doc.rect(MARGIN, 80, CONTENT_W, 2).fill(GOLD);
    doc
      .fillColor(NAVY)
      .fontSize(12)
      .font("Helvetica-Bold")
      .text(isEnglish ? "Important disclaimer" : "Avertissement important", MARGIN, 90);
    doc.moveDown(1);

    doc
      .rect(MARGIN, doc.y, CONTENT_W, 80)
      .fill("#FFF8E8");

    doc
      .fillColor("#5A4A10")
      .fontSize(9)
      .font("Helvetica")
      .text(disclaimer, MARGIN + 12, doc.y + 10, {
        width: CONTENT_W - 24,
        lineGap: 3,
        align: "justify",
      });

    doc.moveDown(2);
    doc
      .fillColor(TEXT_GRAY)
      .fontSize(8)
      .text("TravelGuide AI — travelguide.ai", MARGIN, doc.y, {
        align: "center",
        width: CONTENT_W,
      });

    // ─── FOOTER ON ALL PAGES ──────────────────────────────────────────────────
    addFooterToAllPages(doc, input.destination, W, H, MARGIN);

    doc.end();
  });
}

function isLongTrip(duration: string): boolean {
  return duration === "7j" || duration === "14j" || duration === "1mois";
}

function addPageHeader(
  doc: PDFKit.PDFDocument,
  destination: string,
  W: number,
  MARGIN: number
): void {
  doc.rect(0, 0, W, 65).fill(NAVY);
  doc
    .fillColor("white")
    .fontSize(9)
    .font("Helvetica-Bold")
    .text("TravelGuide AI", MARGIN, 22, { characterSpacing: 1 });
  doc
    .fillColor("rgba(255,255,255,0.5)")
    .fontSize(8)
    .font("Helvetica")
    .text(destination, MARGIN, 38);
}

function addFooterToAllPages(
  doc: PDFKit.PDFDocument,
  destination: string,
  W: number,
  H: number,
  MARGIN: number
): void {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    // Thin gold line above footer
    doc.rect(MARGIN, H - 42, W - MARGIN * 2, 0.5).fill("#C9A84C55");
    // Page number
    doc
      .fillColor("rgba(26,26,46,0.35)")
      .fontSize(7.5)
      .font("Helvetica")
      .text(`${destination} • TravelGuide AI`, MARGIN, H - 32, {
        width: W - MARGIN * 2,
        align: "left",
      });
    doc
      .fillColor("rgba(26,26,46,0.35)")
      .fontSize(7.5)
      .text(`Page ${i + 1}`, MARGIN, H - 32, {
        width: W - MARGIN * 2,
        align: "right",
      });
  }
}
